apiVersion: v1
kind: ConfigMap
metadata:
  name: nemo-guardrails-with-llm-config
data:
  config.yaml: |
    models:
      - type: main
        engine: openai
        parameters:
          openai_api_base: "https://litellm-prod.apps.maas.redhatworkshops.io/v1"
          model_name: "granite-3-2-8b-instruct"
    rails:
      config:
        sensitive_data_detection:
          input:
            entities:
              - EMAIL_ADDRESS
              - PERSON
          output:
            entities:
              - PERSON
      input:
        flows:
          - detect sensitive data on input
      output:
        flows:
          - detect sensitive data on output
  rails.co: |
    # Using built-in sensitive data detection rails
