apiVersion: trustyai.opendatahub.io/v1alpha1
kind: NemoGuardrails
metadata:
  name: nemo-guardrails-with-llm
  annotations:
    security.opendatahub.io/enable-auth: 'true'
spec:
  nemoConfigs:
    - name: nemo-llm-config
      configMaps:
        - nemo-llm-config
  env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: api-token-secret
          key: token
